# fly.toml file generated for goliveview-starter on 2021-11-06T13:26:45+05:30

app = "goliveview-starter"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
    APP_DOMAIN = "https://goliveview-starter.fly.dev"
    APP_LOG_LEVEL = "error"
    APP_DATASOURCE = "file:goliveview-starter.db?cache=shared&_fk=1"
[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
